### ISSUE TITLE
Port a Colombia

### ISSUE THREAD

**Issue by blaggacao** [odoo-venezuela/odoo-venezuela#1]
Buenos Dias

se puede dar una estimacion del trabajo de portar esta localizacion para colombia? me parece que hay varios conceptos muy similares y que de pronto con debido conocimiento del codigo puede resultar una tarea lograble en tiempo util?

M. Gracis

David

**Comment by nhomar** [comment]
Este issue ya se encuentra obsoleto, si consideran que no es así reabrirlo por favor.

Saludos.
