### ISSUE TITLE
Localizacion

### ISSUE THREAD

**Issue by JsusMillan** [odoo-venezuela/odoo-venezuela#2]
Buenas tardes, me gustaria saber para que version de odoo es esta localizacion ?

**Comment by oyepez003** [comment]
Mas allá de que versión es soportada mi pregunta seria si esta activo este proyecto.

**Comment by nhomar** [comment]
2014-12-15 10:21 GMT-06:00 Omar Yepez notifications@github.com:

> Mas allá, de que versión es soportada mi pregunta seria si esta activo
> este proyecto.

Si está activo, pero aún no migrado a la 8.0.

## 

---

Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     http://about.me/nhomar?promo=email_sig

**Comment by nhomar** [comment]
Pueden ver el trabajo en progreso (que será migrado para acá) en éste repositorio.

https://github.com/vauxoo/odoo-venezuela

**Comment by oyepez003** [comment]
Gracias Nhomar por tu pronta respuesta.... eso quiere decir que la rama "master" es para la versión 7 de oddoo?. Nos recomiendas mejor seguir el repositorio de Vauxoo. 

Quisiera saber también como aportar con codigo-pruebas al proyecto.... sinceramente python no es mi principal lenguaje pero quizás oddoo sea una escusa (grandísima) para aprender aun mas sobre este lenguaje.

Saludos cordiales.

**Comment by nhomar** [comment]
El 15 de diciembre de 2014, 11:16, Omar Yepez notifications@github.com
escribió:

> Gracias Nhomar por tu pronta respuesta.... eso quiere decir que la rama
> "master" es para la versión 7 de oddoo? y nos recomiendas mejor seguir el
> repositorio de Vauxoo.
> 
> Quisiera saber también como aportar con codigo-pruebas al proyecto....
> sinceramente python no es mi principal lenguaje pero quizás oddoo sea una
> escusa (grandísima) para aprender aun mas sobre este lenguaje.
> 
> Saludos cordiales.

Sigue el repositorio de nosotros, aún no hemos activado el comunitario por
tiempo :-s (nadie en VE actualemente está financiando lo estamos haciendo
por motus propio).

Cuando esté aquí todo lo anunciaremos.

Saludos.

## 

---

Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     http://about.me/nhomar?promo=email_sig

**Comment by yalayn** [comment]
Buenos Dias. 
De antemano felicitaciones por su trabajo.
Estoy nuevo con el odoo y estoy intentado instalar tu proyecto, logre instalar algunos modulos pero al instalar el resto me da error al parecer es por que el campo x_rif no existe. pero me voy a estructura de la base de datos -> campos y si exite.
Cualquier ayuda que me puedan dar se los agradeceria.
Saludos...

**Comment by nhomar** [comment]
El 10 de febrero de 2015, 10:27, yalayn notifications@github.com escribió:

> Buenos Dias.
> De antemano felicitaciones por su trabajo.
> Estoy nuevo con el odoo y estoy intentado instalar tu proyecto, logre
> instalar algunos modulos pero al instalar el resto me da error al parecer
> es por que el campo x_rif no existe. pero me voy a estructura de la base de
> datos -> campos y si exite.
> Cualquier ayuda que me puedan dar se los agradeceria.
> Saludos...

puedes hacer esta pregunta en algún for por favor, esto no es parte le la
localización.-

saludos,

## 

---

Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     http://about.me/nhomar?promo=email_sig

**Comment by gonzalezmfrank** [comment]
Hola, estoy retomando el asunto de la localización ... branch 7 ... y esto presentando inconvenientes con los libros de venta ... el mensaje es

Sorting field nro_ctrl not found on model fiscal.book.line

tomé los módulos de odoo-venezuela y addons-vauxoo ....

Alguna sugerencia por favor .... Gracias

**Comment by maximus82** [comment]
Hola  @nhomar , yo tambien presento el mismo error que tiene @gonzalezmfrank con respecto al libro de ventas.

1 Creo un libro de ventas.
2 Agrego la descripcion y el periodo.
3 Guardo
4 Click en Actualizar Libro y me da el error:

ValueError: Sorting field nro_ctrl not found on model fiscal.book.line

**Comment by nhomar** [comment]
Hola @maximus82 @gonzalezmfrank 

Como menciono arriba en éste hilo, aún no hemos migrado, el branch 7 lo tenemos en producción leyendo desde launchpad todavía.

Voy a buscar un tiempo para comenzar a usar github pero no será al menos en los próximos 15 días.

Si formulan un hilo por tópico con todo gusto los apoyamos, tengan en cuenta que una de las razones por las que no se ha migrado es que no contamos con muchos cliente que financien nuestro tiempo, por consiguiente si consideran que pueden acompañar los issues reportados con un PR/MP sería agradecido así entre todos la dejamos operativa.

Saludos.

PS: Estoy cerrando éste issue para poder marcarla como no resuelto es solo una pregunta.
